parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_NAME): ''
    env(DATABASE_HOST): ''
    env(DATABASE_PORT): ''
    env(DATABASE_USER): ''
    env(DATABASE_PASS): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        dbname: '%env(resolve:DATABASE_NAME)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASS)%'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App